name: "Code Quality Analysis"

on: [push, pull_request]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Master Ruleset
        run: curl -sSL https://raw.githubusercontent.com/wouterpxl/pxl-code-quality-analysis/refs/heads/main/pmd-rules.xml -o pmd-rules.xml
        
      - name: Run Tests
        run: ./gradlew test

      - name: Check Test Coverage
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
        
      - name: Run PMD (Java)
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'pmd-rules.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
          uploadSarifReport: true

      - name: Upload PMD results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
          category: pmd-java
